"""New Migration

Revision ID: 4391bc40282e
Revises: 
Create Date: 2022-04-15 01:09:43.956714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4391bc40282e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_table('userInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=64), nullable=True),
    sa.Column('diet_style', sa.String(length=64), nullable=True),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('bmr', sa.Integer(), nullable=True),
    sa.Column('bmr7', sa.Integer(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('weekly_calories', sa.Integer(), nullable=True),
    sa.Column('daily_protein', sa.Integer(), nullable=True),
    sa.Column('daily_carbs', sa.Integer(), nullable=True),
    sa.Column('daily_fat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userInfo_id'), 'userInfo', ['id'], unique=False)
    op.create_table('food_eaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_eaten_id'), 'food_eaten', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_eaten_id'), table_name='food_eaten')
    op.drop_table('food_eaten')
    op.drop_index(op.f('ix_userInfo_id'), table_name='userInfo')
    op.drop_table('userInfo')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
